# Generated by Django 3.2.5 on 2021-07-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_message', models.TextField()),
                ('title_tips', models.TextField(blank=True)),
                ('author_tips', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('year_written', models.IntegerField()),
                ('year_read', models.PositiveIntegerField()),
                ('part_of_series', models.BooleanField()),
                ('cover_description', models.TextField()),
                ('genre', models.CharField(max_length=50)),
                ('plot_details', models.TextField()),
                ('quotes', models.TextField()),
                ('additional_notes', models.TextField()),
            ],
        ),
    ]
