# Generated by Django 3.2.5 on 2021-07-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='opening_message',
        ),
        migrations.AlterField(
            model_name='book',
            name='part_of_series',
            field=models.CharField(max_length=50),
        ),
    ]
