# Generated by Django 3.2.5 on 2021-07-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210722_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('action', 'Action and Adventure'), ('classics', 'Classics'), ('comic', 'Comic Book'), ('mystery', 'Mystery'), ('fantasy', 'Fantasy'), ('hist fiction', 'Historical Fiction'), ('horror', 'Horror'), ('romance', 'Romance'), ('sci-fi', 'Sci-Fi'), ('thriller', 'Thriller'), ('biography', 'Biography'), ('history', 'History'), ('memoir', 'Memoir'), ('poetry', 'Poetry'), ('self-help', 'Self-Help'), ('non-fiction', 'Non-fiction')], max_length=50, null=True),
        ),
    ]
