# Generated by Django 3.2.5 on 2021-07-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210724_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='part_of_series',
            field=models.BooleanField(choices=[(None, "Can't remember"), (True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
