# Generated by Django 3.2.5 on 2021-07-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_part_of_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_read',
            field=models.PositiveIntegerField(default=2000),
            preserve_default=False,
        ),
    ]
