# Generated by Django 3.2.5 on 2021-08-01 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fileds_filled',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(11)]),
            preserve_default=False,
        ),
    ]
