# Generated by Django 3.2.5 on 2021-08-01 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_book_fileds_filled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='fileds_filled',
            new_name='filled_fields_count',
        ),
    ]
