# Generated by Django 3.2.6 on 2021-08-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_modified',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='last_modified',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
