# Generated by Django 3.2.6 on 2021-08-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20210820_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
