# Generated by Django 3.2.5 on 2021-08-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
